import { Annotation } from '@langchain/langgraph';

const replace = (defaultValue = null) => Annotation({ reducer: (_left, right) => right, default: () => defaultValue });
const append = () => Annotation({ reducer: (left = [], right = []) => [...left, ...right], default: () => [] });

export const PlanReviewState = Annotation.Root({
  runId: replace(),
  userId: replace(),
  profileId: replace(),
  expectedPlanReviewSnapshotHash: replace(),
  planReviewSnapshotHash: replace(),
  sourceBinding: replace(),
  correlationId: replace(),
  traceId: replace(),
  startedAt: replace(),
  profile: replace(),
  profileContext: replace(),
  recommendation: replace(),
  currentState: replace(),
  recommendationSummary: replace(),
  freshness: replace(),
  goalSummary: replace(),
  evidencePacket: replace(),
  researchNeed: replace(),
  researchBrief: replace(),
  researchArtifact: replace(),
  researchVerification: replace(),
  researchFailure: replace(),
  researchScenario: replace(),
  requestedChecks: replace([]),
  toolResults: replace({}),
  toolCallCount: replace(0),
  modelCallCount: replace(0),
  tokenUsage: replace(0),
  toolCallCounts: replace({}),
  stepCount: replace(0),
  repeatedRequests: replace([]),
  findings: replace([]),
  recommendedAction: replace('INSUFFICIENT_EVIDENCE'),
  explanation: replace(),
  review: replace(),
  planner: replace({ provider: 'DETERMINISTIC', model: null, fallback: true }),
  validation: replace({ valid: false, errors: [] }),
  evidenceVerification: replace({ valid: false, unknownEvidenceIds: [], injectionDetected: false }),
  policy: replace({ allowed: false, reasonCodes: [] }),
  errors: append(),
  status: replace('RUNNING'),
  resumeCheckpoint: replace(null),
});
