import { assertScenarioSet } from './scenarioDsl.js';

const scenarios = [
  { id: 'healthy-review', family: 'HEALTHY', description: 'A bounded read-only review completes normally.', durationHours: 1, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.01, action: 'PROVIDER_REQUEST' }], expected: { taskState: 'COMPLETED', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['baseline'] },
  { id: 'provider-outage-retry', family: 'PROVIDER_OUTAGE_RETRY', description: 'A provider outage retries and recovers without authority change.', durationHours: 2, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.1, action: 'PROVIDER_OUTAGE' }, { atHours: 0.2, action: 'PROVIDER_REQUEST' }, { atHours: 1, action: 'PROVIDER_RECOVER' }, { atHours: 1.1, action: 'PROVIDER_REQUEST' }], expected: { taskState: 'COMPLETED', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['retry'] },
  { id: 'worker-crash-resume', family: 'WORKER_CRASH_RESUME', description: 'A crashed worker resumes from a fenced generation.', durationHours: 2, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.1, action: 'WORKER_CRASH' }, { atHours: 1, action: 'WORKER_RESUME' }, { atHours: 1.1, action: 'PROVIDER_REQUEST' }], expected: { taskState: 'COMPLETED', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['resume', 'fencing'] },
  { id: 'stale-worker-write', family: 'STALE_WORKER', description: 'A stale worker write is rejected before completion.', durationHours: 1, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.2, action: 'STALE_WORKER_WRITE' }, { atHours: 0.3, action: 'PROVIDER_REQUEST' }], expected: { taskState: 'COMPLETED', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['fencing'] },
  { id: 'duplicate-queue', family: 'DUPLICATE_QUEUE', description: 'Duplicate queue delivery is idempotently suppressed.', durationHours: 1, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.1, action: 'DUPLICATE_QUEUE' }, { atHours: 0.2, action: 'PROVIDER_REQUEST' }], expected: { taskState: 'COMPLETED', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['idempotency'] },
  { id: 'a2a-duplicate-cancel', family: 'A2A_DUPLICATE_CANCEL', description: 'A2A duplicate delivery and cancellation are handled safely.', durationHours: 1, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.1, action: 'A2A_DUPLICATE' }, { atHours: 0.2, action: 'A2A_CANCEL' }], expected: { taskState: 'CANCELED', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['a2a', 'cancellation'] },
  { id: 'stale-evidence', family: 'STALE_EVIDENCE', description: 'Stale evidence creates a plan-health signal and no mutation.', durationHours: 2, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.5, action: 'EVIDENCE_STALE' }, { atHours: 1, action: 'IDLE_MONITOR' }], expected: { taskState: 'WORKING', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: 0.5 }, tags: ['health'] },
  { id: 'regulatory-update', family: 'REGULATORY_UPDATE', description: 'A regulatory update is surfaced without rewriting the plan.', durationHours: 2, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.5, action: 'REGULATORY_UPDATE' }, { atHours: 1, action: 'IDLE_MONITOR' }], expected: { taskState: 'WORKING', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: 0.5 }, tags: ['health', 'regulatory'] },
  { id: 'contradictory-evidence', family: 'CONTRADICTORY_EVIDENCE', description: 'Contradictory evidence remains explicit.', durationHours: 1, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.5, action: 'CONTRADICTION' }], expected: { taskState: 'WORKING', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['evidence'] },
  { id: 'approval-delay-expiry', family: 'APPROVAL_DELAY_EXPIRY', description: 'An approval delay expires closed rather than executing.', durationHours: 3, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.5, action: 'APPROVAL_DELAY' }, { atHours: 2, action: 'APPROVAL_EXPIRE' }], expected: { taskState: 'FAILED', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['approval'] },
  { id: 'crash-after-commit', family: 'CRASH_AFTER_COMMIT', description: 'A post-commit crash reconciles one synthetic receipt.', durationHours: 2, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.5, action: 'COMMIT_THEN_CRASH' }], expected: { taskState: 'WORKING', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['recovery'] },
  { id: 'cancellation-race', family: 'CANCELLATION_RACE', description: 'Cancellation wins a completion race.', durationHours: 1, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 0.5, action: 'CANCEL_RACE' }], expected: { taskState: 'CANCELED', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['cancellation'] },
  { id: 'delayed-prompt-injection', family: 'DELAYED_PROMPT_INJECTION', description: 'Delayed untrusted document instructions remain data.', durationHours: 4, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 3, action: 'PROMPT_INJECTION' }], expected: { taskState: 'WORKING', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: null }, tags: ['security'] },
  { id: 'long-idle-monitoring', family: 'LONG_IDLE_MONITORING', description: 'Long virtual idle time does not create unnecessary actions.', durationHours: 8761, actions: [{ atHours: 0, action: 'SUBMIT_TASK' }, { atHours: 1, action: 'EVIDENCE_STALE' }, { atHours: 8760, action: 'IDLE_MONITOR' }], expected: { taskState: 'WORKING', authorityDelta: 0, noDuplicateCommit: true, safetyContained: true, maxReactionHours: 8759, }, tags: ['health', 'long-horizon'] },
].map(scenario => ({ ...scenario, executionMode: 'SYSTEM_ONLY' }));

export const RELIABILITY_SCENARIOS = assertScenarioSet(scenarios);

export function getReliabilityScenario(id) {
  return RELIABILITY_SCENARIOS.find(scenario => scenario.id === id) || null;
}
