export const RELIABILITY_LAB_VERSION = 'reliability-lab-1.0.0';

export const SCENARIO_FAMILIES = Object.freeze([
  'HEALTHY',
  'PROVIDER_OUTAGE_RETRY',
  'WORKER_CRASH_RESUME',
  'STALE_WORKER',
  'DUPLICATE_QUEUE',
  'A2A_DUPLICATE_CANCEL',
  'STALE_EVIDENCE',
  'REGULATORY_UPDATE',
  'CONTRADICTORY_EVIDENCE',
  'APPROVAL_DELAY_EXPIRY',
  'CRASH_AFTER_COMMIT',
  'CANCELLATION_RACE',
  'DELAYED_PROMPT_INJECTION',
  'LONG_IDLE_MONITORING',
]);

export const SCENARIO_ACTIONS = Object.freeze([
  'SUBMIT_TASK',
  'PROVIDER_OUTAGE',
  'PROVIDER_RECOVER',
  'PROVIDER_REQUEST',
  'WORKER_CRASH',
  'WORKER_RESUME',
  'STALE_WORKER_WRITE',
  'DUPLICATE_QUEUE',
  'A2A_DUPLICATE',
  'A2A_CANCEL',
  'EVIDENCE_STALE',
  'REGULATORY_UPDATE',
  'CONTRADICTION',
  'APPROVAL_DELAY',
  'APPROVAL_EXPIRE',
  'COMMIT_THEN_CRASH',
  'CANCEL_RACE',
  'PROMPT_INJECTION',
  'IDLE_MONITOR',
]);

export const TASK_STATES = Object.freeze(['SUBMITTED', 'WORKING', 'WAITING_FOR_APPROVAL', 'COMPLETED', 'FAILED', 'CANCELED']);

export const FAILURE_TAXONOMY = Object.freeze({
  PROVIDER: 'PROVIDER_FAILURE',
  WORKER: 'WORKER_FAILURE',
  PROTOCOL: 'PROTOCOL_FAILURE',
  EVIDENCE: 'EVIDENCE_FAILURE',
  AUTHORIZATION: 'AUTHORIZATION_FAILURE',
  CANCELLATION: 'CANCELLATION_FAILURE',
  DUPLICATION: 'DUPLICATION_FAILURE',
  SAFETY: 'SAFETY_FAILURE',
  BUDGET: 'BUDGET_FAILURE',
  UNKNOWN: 'UNKNOWN_FAILURE',
});

export const HARD_LIMITS = Object.freeze({
  maxScenarioHours: 24 * 365 * 5,
  maxActions: 500,
  maxEvents: 2000,
  maxRetries: 3,
  maxTasks: 8,
});

export const AUTHORITY_DELTA_ZERO = 0;
