apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wealthgenie

resources:
  - namespace.yaml
  - configmap.yaml
  - mongodb/pvc.yaml
  - mongodb/statefulset.yaml
  - mongodb/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - ml-service/deployment.yaml
  - ml-service/service.yaml
  - server/deployment.yaml
  - server/service.yaml
  - server/hpa.yaml
  - agent-worker/deployment.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml
